---
id: study-material-20130203
base_name: how-to-handle-million-data
tags: []
presentation_date: 
version: 1.0.0
licenses: [CC BY 3.0]
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
author: Masafumi Yokoyama
  markup_language: :rd
  name: Masafumi Yokoyama
  email: myokoym@gmail.com
  rubygems_user: myokoym
  slideshare_user: myokoym
  speaker_deck_user: myokoym
