---
id: study-material-20130203
base_name: how-to-handle-million-data
tags:
- rabbit
- unix
presentation_date: 
version: 1.1.1
licenses:
- CC BY 3.0
slideshare_id: study-material-20130203-16721191
speaker_deck_id: 
ustream_id: 
vimeo_id: 
author:
  markup_language: :rd
  name: Masafumi Yokoyama
  email: myokoym@gmail.com
  rubygems_user: myokoym
  slideshare_user: myokoym
  speaker_deck_user: myokoym
